
language: python

env:
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=3.5-dev

# install only tox, tox will take care of installing the rest of the dependencies
install:
  - pip install tox

# run tests
script: tox

notifications:
  email:
  - samuel@innovativetravel.eu
